services:
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=development
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    stdin_open: true
    tty: true
    command: npm start

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_key
      - DB_HOST=92.53.105.112
      - DB_PORT=3306
      - DB_USER=gen_user
      - DB_PASSWORD=0edMjCX^NIR+kp
      - DB_NAME=default_db
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - app-network
    command: npm run start

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    command: /bin/sh -c "sleep 10 && nginx -g 'daemon off;'"

networks:
  app-network:
    driver: bridge
