version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/app/frontend/build
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: always

  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    volumes:
      - ./frontend/build:/app/build
    networks:
      - app-network
    restart: always
    command: serve -s build -l 3000

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_key
      - DB_HOST=92.53.105.112
      - DB_PORT=3306
      - DB_USER=gen_user
      - DB_PASSWORD=0edMjCX^NIR+kp
      - DB_NAME=default_db
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - app-network
    restart: always
    command: npm run start

networks:
  app-network:
    driver: bridge
