services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: backend-build
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/backend/src
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ivastrameds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
